name: fluttertemplate
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # 核心MMVM框架
  stacked: 2.2.3
  stacked_hooks: 0.2.1
  stacked_services: 0.8.8

  # services
  share_plus: 2.1.4
  dio: 4.0.0
  dio_http2_adapter: 2.0.0
  url_launcher: 6.0.3
  shared_preferences: 2.0.6
  connectivity: 3.0.6
  app_settings: 4.1.1
  flutter_dotenv: 5.0.1
  package_info: 2.0.2

  flutter_spinkit: 5.0.0
  path_provider: 2.0.2
  rxdart: ^0.26.0
  provider: 5.0.0

  flutter_screenutil: ^5.0.0
  fluttertoast: 8.0.8
  flutter_inner_drawer: 1.0.0+1
  flutter_swiper: 1.1.6
  
  permission_handler: 7.1.0
  built_value: ^8.1.0
  get_it: 7.1.3
  quiver: 3.0.1
  hive: 2.0.4
  hive_flutter: 1.1.0
  device_info: 2.0.2
  shimmer: 2.0.0

  http_parser: 4.0.0
  mime: 1.0.0
  get: 4.1.4
  # 动画
  flare_flutter: 3.0.1
  # 动画
  lottie: 1.1.0
  qr_flutter: 4.0.0
  web_socket_channel: 2.1.0
  protobuf: 2.0.0
  cached_network_image: 3.0.0
  focus_detector: 2.0.0
  freezed_annotation: 0.14.2
  json_annotation: 4.0.1
  date_format: 2.0.2
  flutter_local_notifications: 6.0.0
  flutter_picker: 2.0.2
  numberpicker: 2.1.1
  # 日志
  logging: 1.0.1
  # 日志
  fimber: 0.6.1
  feedback: 2.0.0
  feature_discovery: 0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 数据mock
  build_runner: ^2.0.1
  stacked_generator: ^0.4.1
  hive_generator: ^1.1.0
  json_serializable: ^4.1.2
  built_value_generator: ^8.0.6
  freezed: ^0.14.2
  mockito: ^5.0.0
  logger: 1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lang/zh.json
    - assets/lang/en.json

    - assets/audio/viper.mp3
    - assets/audio/bgaudio.mp3

    - assets/webview/dist/index.html
    - assets/webview/dist/
    - assets/webview/dist/css/
    - assets/webview/dist/js/
    - assets/webview/dist/musicXML/

    - assets/animations/
    - assets/animations/lottie/
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

