name: chinaculture
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: "3.0.3"
  flutter_spinkit: "^4.0.0"
  url_launcher: "5.4.2"
  transparent_image: "1.0.0"
  fluro: "1.5.1"
  firebase_analytics: "5.0.11"
  event_bus: "1.1.0"
  shared_preferences: "0.5.3"
  path_provider: "1.6.5"
  rxdart: "0.23.1"
  provider: "3.2.0"
  oktoast: "2.2.0"
  flutter_inner_drawer: "0.5.4"
  flutter_swiper: "1.1.6"
  connectivity: "0.4.8+1"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # mock data
  mockito: "^4.1.1"
  build_runner: "^1.0.0"
  json_serializable: "^3.2.0"


flutter:
  uses-material-design: true
  assets:
    - assets/ifredom.jpg
    - assets/image/
    - assets/image/custom/
  
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
