name: fluttertemplate
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core MMVM
  stacked: 2.2.3
  stacked_hooks: 0.2.1
  stacked_services: 0.8.13

  # services
  dio: 4.0.0
  dio_http2_adapter: 2.0.0
  url_launcher: 6.0.3
  shared_preferences: 2.0.6
  share: 2.0.4
  connectivity: 3.0.6
  device_info: 2.0.2
  flutter_dotenv: 5.0.2
  app_settings: 4.1.1
  package_info: 2.0.2
  flutter_keyboard_visibility: 5.1.0
  freezed_annotation: 0.14.2

  # three modules
  meta: 1.3.0
  rxdart: ^0.27.0
  built_value: ^8.1.0
  built_collection: ^5.1.0
  get_it: 7.2.0
  get: 4.3.8
  path_provider: 2.0.2
  provider: 5.0.0
  permission_handler: 7.1.0
  logging: 1.0.1
  fluttertoast: 8.0.8

  feedback: 2.2.1
  flutter_spinkit: 5.1.0
  http_parser: 4.0.0
  mime: 1.0.1
  shimmer: 2.0.0
  # utils
  quiver: 3.0.1
  # animation
  flare_flutter: 3.0.1
  # animation
  lottie: 1.1.0
  qr_flutter: 4.0.0
  web_socket_channel: 2.1.0
  cached_network_image: 3.1.0

  json_annotation: 4.0.1
  flutter_local_notifications: 9.1.4
  flutter_midi: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: ^2.0.1
  stacked_generator: 0.5.0
  json_serializable: 4.1.3
  built_value_generator: ^8.0.6
  freezed: ^0.14.2
  # mock data
  mockito: ^5.0.0
  logger: 1.0.0
  screenshot: 1.2.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lang/zh.json
    - assets/lang/en.json

    - assets/sounds/Piano.sf2

    - assets/audio/viper.mp3
    - assets/audio/tapbutton.mp3

    - assets/webview/dist/index.html
    - assets/webview/dist/
    - assets/webview/dist/css/
    - assets/webview/dist/js/
    - assets/webview/dist/musicXML/

    - assets/animations/
    - assets/animations/lottie/
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
