name: template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: 3.0.9
  flutter_spinkit: 4.1.2
  url_launcher: 5.4.2
  event_bus: 1.1.0
  shared_preferences: 0.5.3
  path_provider: 1.6.5
  flutter_cupertino_date_picker: 1.0.12
  orientation: 1.1.0
  rxdart: 0.23.1
  provider: 4.0.4
  stacked: 1.7.4
  oktoast: 2.3.1
  flutter_inner_drawer: 0.5.4
  flutter_swiper: 1.1.6
  city_pickers: 0.1.30
  connectivity: 0.4.8+1
  permission_handler: 4.4.0+hotfix.2
  built_value: 7.0.4
  get_it: 4.0.4
  hive: ^1.4.1+1
  device_info: 0.4.2+1
  shimmer: 1.1.0
  app_settings: 3.0.1
  flutter_platform_widgets: 0.32.4
  flare_flutter: 2.0.1
  http_parser: 3.1.3
  mime: 0.9.6+3
  json_annotation: 3.0.1
  fijkplayer: 0.7.0
  flutter_bluetooth_basic: 0.1.3
  barcode_scan: 2.0.1
  qr_flutter: 3.1.0
  protobuf: 1.0.1
  audioplayers: 0.14.0
  nested: 0.0.4
  cached_network_image: 2.0.0
  # 蓝牙插件
  flutter_ble_lib: 2.2.5
  # 蓝牙设备模拟器，仅适用于 flutter_ble_lib
  blemulator: 1.1.3
  # 日志
  logging: 0.11.4
  # 路由导航
  get: 2.10.1
  focus_detector: 1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 数据mock
  mockito: ^4.1.1
  build_runner: ^1.7.2
  json_serializable: ^3.2.0
  built_value_generator: ^7.0.4
  hive_generator: ^0.7.0
  pedantic: ^1.8.0
  logger: ^0.9.1

  flutter_inappwebview: 2.1.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
